### PR TITLE
SearchQuery made asynchronous

### PR DESCRIPTION
**Pull request by Maharba**
WebClient was replaced with HttpClient, also the following NuGet packages were added in order to make the SearchQuery method asynchronous.
-Microsoft.Bcl.Async
Dependencies:
-Microsoft.Bcl
-Microsoft.Bcl.Build

### CODE REVIEW

**Comment by AlenToma** [comment]
could you also take a look at my issue

**Comment by mrklintscher** [comment]
Dependencies will not work on mobile devices.

**Comment by AlenToma** [comment]
it dose not matter i want to be able to past this url https://www.youtube.com/watch?v=wfWIs2gFTAM
and get all videos that shows upp there. 
so the regexp have to be modified and extract the title etc 
here is a try i did and failed

```csharp
 var link = querystring.Contains("http") ? querystring : $"https://www.youtube.com/results?search_query={querystring}&page={i}";
 // Search address
 string html = webclient.DownloadString(link);
// Search string
 string pattern  = !querystring.Contains("http") ?
 "<div class=\"yt-lockup-content\">.*?title=\"(?<NAME>.*?)\".*?yt-uix-sessionlink" : 
"(?:.+?)?(?:\\/v\\/|watch\\/|\\?v=|\\&v=|youtu\\.be\\/|\\/v=|^youtu\\.be\\/)([a-zA-Z0-9_-]{11})+";
```

**Comment by mrklintscher** [comment]
Your question does not belong to the project.


Von meinem iPhone gesendet

**Pull request closed without merging**
